server.port: 8080

spring:
  data:
    redis:
      url: rediss://default:fab5b4cbb0ff44bc81502f2788774043@apn1-great-eel-33212.upstash.io:33212
  datasource:
    url: jdbc:mariadb://localhost:3306/tot-mysj
    username: root
    password:
  jpa.hibernate.ddl-auto: update